package mztech.classwork;

public class CharStringNumber {
    public static void main (String[] args){
        //Number
        Integer l = 5; // boxes int to an Integer Object
        l = l + 10; // unboxes integer to a int
        System.out.println(l);
        Integer m = 10;
        int ten = 10;

        //Random
        System.out.println("Random" + Math.random());

        //equals()
        System.out.println(l.equals(m));// l == m

        //toString ()
        System.out.println(l);// converts int to string
        System.out.println(12);

        //Integer.parseInt()
        String five = "5";
        System.out.println(Integer.parseInt(five));// converts string to integer

        //concat adds two string
        System.out.println(five.concat(ten + ""));// + "" after int makes it string
        //concat
        String firstName = "John";
        String lastName = "Doe";
        System.out.println("Without concat method" + firstName + lastName);
        System.out.println("With concat method" + firstName.concat(lastName));


        //xxxValue()
        //returns byte primitive data type
        System.out.println(l.longValue());

        //compareTo() 0 for equal, 1 for grater than and -1 for less than
        System.out.println(l.compareTo(3));


        char letter = 'm';
        char letterTwo = 'Z';
        System.out.println("Turn this" + letter + "letter to upper case " + Character.toUpperCase(letter));
        System.out.println("Turn this" + letterTwo + "letter to lower case " + Character.toLowerCase(letterTwo));

        //String
        String name = "Jarin";
        System.out.println("My name is " + name);
        System.out.println("====");

        //Convert Char array to string
        char[] company = {'M', 'Z', 'T', 'e', 'c', 'h'};
        for (char x : company) {
            System.out.print(x);
        }
        System.out.println();

        //printing ascii value
        System.out.println("ASCII Value: " + (int) 'A'); // 65
        //printing hash code
        System.out.println(name.hashCode());// name = "Jarin"
        //hashCode in Java is a function that returns the hashcode value of an object on calling.
        // It returns an integer or a 4 bytes value which is generated by the hashing algorithm.

        //isWhitespace
        //System.out.println(name.isWhitespace());

        //Returns Boolean
        String subject = "Math";
        String subjectTwo = "Science";
        String subjectThree = "math";
        System.out.println("Is" + subject + " equals to " + subjectTwo + " : " + subject.equals(subjectTwo));
        System.out.println("Is" + subject + " equals to " + subjectThree + " (without ignoring case) : " + subject.equals(subjectThree));
        System.out.println("Is" + subject + " equals to " + subjectThree + " (ignoring case) : " + subject.equalsIgnoreCase(subjectThree));
        System.out.println("Is" + subject + " equals to " + subjectThree + " (ignoring case without using equalsIgnoreCase method) : " + subject.toUpperCase().equals(subjectThree.toLowerCase()));

        //Substring
        // M a t h
        // 0 1 2 3

        String giantString = "Afoxjumpedoverafencenmidnightofjulysixteenththatnobodyknows";
        //print form 5th character to end
        //Mztech
        // 2 to 6-1
        //length starts from 1 but index starts with 0
        //5, 74-1
        System.out.println("The length of this String " + giantString + "is" + giantString.length());
        //System.out.println("Print first 3 character of " + giantString + "is" + giantString.substring(5 , (giantString.length()-1)));
        System.out.println("Print first 3 character of " + giantString + "is" + giantString.substring(0, 3));

        String companysfd = "Mztech";


    }
}
